# -*- coding: utf-8 -*-
"""DAT-5-PYTHON-AND-MACHINE-LEARNING-PAGE-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqShFUOZe8j85yy9Ufk2F238wir-Ihao
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, ConfusionMatrixDisplay, roc_curve, auc

print("="*80)
print("TITANIC SURVIVAL PREDICTION - CLASSIFICATION")
print("="*80)

# ==========================================================
# STEP 2 - LOAD DATASET
# ==========================================================

df = pd.read_csv("Titanic-Dataset (1).csv")
#

# ------------------------------------------------------------------
# Load Dataset
# ------------------------------------------------------------------
df = pd.read_csv("Titanic-Dataset (1).csv")

print(df.head())
print(df.info())
print(df.describe(include="all"))
print("\nMissing Values")
print(df.isnull().sum())

# ------------------------------------------------------------------
# Data Cleaning
# ------------------------------------------------------------------
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df["Fare"] = df["Fare"].fillna(df["Fare"].median())
df.drop(columns=["Cabin"], inplace=True, errors="ignore")

# ------------------------------------------------------------------
# Exploratory Data Analysis
# ------------------------------------------------------------------
plt.figure(figsize=(5,4))
sns.countplot(data=df, x="Survived")
plt.title("Survival Count")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Sex", hue="Survived")
plt.title("Survival by Gender")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="Pclass", hue="Survived")
plt.title("Survival by Passenger Class")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------
# Encoding
# ------------------------------------------------------------------
df["Sex"] = df["Sex"].map({"male":0,"female":1})
df = pd.get_dummies(df, columns=["Embarked"], drop_first=True)

# ------------------------------------------------------------------
# Feature Selection
# ------------------------------------------------------------------
drop_cols = ["PassengerId","Name","Ticket","Survived"]
X = df.drop(columns=[c for c in drop_cols if c in df.columns])
y = df["Survived"]

# ------------------------------------------------------------------
# Split Data
# ------------------------------------------------------------------
X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42,stratify=y
)

# ------------------------------------------------------------------
# Scale Numeric Features
# ------------------------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# ------------------------------------------------------------------
# Models
# ------------------------------------------------------------------
models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(probability=True, random_state=42)
}

results = []

for name, model in models.items():
    print("\n"+"-"*60)
    print(name)
    print("-"*60)

    model.fit(X_train,y_train)
    pred = model.predict(X_test)

    acc = accuracy_score(y_test,pred)
    results.append([name,acc])

    print("Accuracy:",round(acc,4))
    print(classification_report(y_test,pred))

    cm = confusion_matrix(y_test,pred)
    disp = ConfusionMatrixDisplay(cm)
    disp.plot()
    plt.title(name)
    plt.show()

    if hasattr(model,"predict_proba"):
        prob = model.predict_proba(X_test)[:,1]
        fpr,tpr,_ = roc_curve(y_test,prob)
        roc_auc = auc(fpr,tpr)

        plt.figure(figsize=(5,5))
        plt.plot(fpr,tpr,label=f"AUC={roc_auc:.3f}")
        plt.plot([0,1],[0,1],"--")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title(name+" ROC Curve")
        plt.legend()
        plt.tight_layout()
        plt.show()

# ------------------------------------------------------------------
# Accuracy Comparison
# ------------------------------------------------------------------
result_df = pd.DataFrame(results,columns=["Model","Accuracy"])
result_df = result_df.sort_values("Accuracy",ascending=False)

print("\nModel Comparison")
print(result_df)

plt.figure(figsize=(8,4))
plt.bar(result_df["Model"],result_df["Accuracy"])
plt.xticks(rotation=15)
plt.ylim(0,1)
plt.title("Model Accuracy Comparison")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------
# Best Model
# ------------------------------------------------------------------
best_name = result_df.iloc[0]["Model"]
print("\nBest Model:",best_name)

best_model = models[best_name]
predictions = best_model.predict(X_test)

output = pd.DataFrame({
    "Actual":y_test.values,
    "Predicted":predictions
})

output.to_csv("Titanic_Predictions.csv",index=False)

print("\nPredictions saved as Titanic_Predictions.csv")

print("\nProgram Completed Successfully.")