# -*- coding: utf-8 -*-
"""DAY-5-PYTHON-AND-MACHINE-LEARNING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ca7M-mEyJS8x0ZEWRbrZCMS2NcWF-suZ
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ==========================================================
# STEP 2 - LOAD DATASET
# ==========================================================

df = pd.read_csv("kc_house_data (1).csv")

# ------------------------------------------
# Input and Target
# ------------------------------------------

X = df[["bedrooms","bathrooms"]]
y = df["price"]

print("FIRST FIVE RECORDS")
print(df.head())

print(df.shape)

print(df.columns)

print(df.describe)

print(df.isnull().sum())

print(df.duplicated().sum())

print(df.tail())

print(df["id"].value_counts())

print(df.dtypes)

y = df["zipcode"]
print(y.head())

print(df["sqft_living15"].value_counts())

# ------------------------------------------
# Split Dataset
# ------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape :", X_test.shape)

# ------------------------------------------
# Input and Target
# ------------------------------------------

X = df[["bedrooms","bathrooms"]]
y = df["price"]

# ------------------------------------------
# Train Model
# ------------------------------------------A

model = LinearRegression()

model.fit(X_train, y_train)

print("\nModel Training Completed")

# ------------------------------------------
# Prediction
# ------------------------------------------

y_pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

print(comparison.head())

# ------------------------------------------
# Evaluation
# ------------------------------------------

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("\nEvaluation Metrics")
print("-" * 40)
print("MAE :", mae)
print("MSE :", mse)
print("RMSE :", rmse)
print("R2 Score :", r2)

# ------------------------------------------
# Coefficients
# ------------------------------------------

coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print("\nFeature Importance")
print(coef)

# ------------------------------------------
# Actual vs Predicted Plot
# ------------------------------------------

plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual House Price")

plt.ylabel("Predicted House Price")

plt.title("Actual vs Predicted")

plt.grid(True)

plt.show()

# ------------------------------------------
# Residual Plot
# ------------------------------------------

residuals = y_test - y_pred

plt.figure(figsize=(8,6))

plt.scatter(y_pred, residuals)

plt.axhline(y=0,color='red')

plt.xlabel("Predicted")

plt.ylabel("Residual")

plt.title("Residual Plot")

plt.grid(True)

plt.show()

# ------------------------------------------
# New Prediction
# ------------------------------------------


price = ({
    'bedrooms': [3],
    'bathrooms': [1],

})

new_data = pd.DataFrame(price)

prediction = model.predict(new_data)

print("\nPredicted price :", prediction[0])